server:
  port: ${SERVER_PORT}

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  instance:
    prefer-ip-address: true

spring:
  config:
    import: optional:.env[.properties]